/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package beatmaker;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
//import org.assertj.swing.*;

class AppTest {
    /**
     * Suppose to test if all audios plays.
     */
    @Test void audioPlay() {

    }

    @Test void buttonsWork(){

    }
}
