/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package beatmaker;

public class App {
    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(new Runnable(){
            public void run(){
                UI ui = new UI();
                ui.show();
            }
        });
    }
}
